basic/controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Reserva;
use app\models\Veiculo;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Parque;
use app\models\ParqueTipoLugar;
use yii\web\AssetManager;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'access2' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['mostraparque'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->getIdentity()->tipoUtilizador=='Condutor' ||
                            Yii::$app->user->getIdentity()->tipoUtilizador=='Admin' ;
                        }
                    ],
                    [
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['get'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionOnlineparks(){
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $model = Parque::find()->asArray()->all();
        return [
                'message'=>'ok',
                'parks'  =>$model
            ];
    }

    public function actionMostraparque(){
        $r = Yii::$app->request;
        /*
        $parqueId = $r->get('id');
        $origem   = $r->get('origem');
        $tempo1   = $r->get('tempo1');
        $distancia1= $r->get('distancia1');
        $destino   = $r->get('destino');
        $tempo2   = $r->get('tempo2');
        $distancia2= $r->get('distancia2');*/

        $parque = Parque::find()
                    ->innerJoin('parque_tipo_lugar','parque_tipo_lugar.id_parque=parque.id')
                    ->select('parque.*,sum(parque_tipo_lugar.total_lugares) as total_lugares')
                    ->where(['parque.id'=>$r->get('id'),
                    //         'parque_tipo_lugar.id_tipo_lugar'=>1
                    ])
                    ->asArray()->one();

        $lugares = ParqueTipoLugar::find()
                    ->innerJoin('tipo_lugar','tipo_lugar.id=parque_tipo_lugar.id_tipo_lugar')
                    ->select('parque_tipo_lugar.*,tipo_lugar.descricao')
                    ->where(['parque_tipo_lugar.id_parque'=>$r->get('id')])
                    ->asArray()->all();

        $veiculos = Veiculo::find()
                    ->where(['veiculo.id_utilizador'=>Yii::$app->user->id])
                    ->asArray()->all();


        $reserva = new Reserva();


        $reserva->data_reserva = date('Y-m-d H:i:s');;
        $reserva->id_parque= $r->get('id');

        return $this->render('mostraparque',[
            'get'=>$r->get(),
            'reserva'=>$reserva,
            'parque'=>$parque,
            'lugares'=>$lugares,
            'veiculos'=>$veiculos
        ]);
    }

    public function actionIndex()
    {
        if (\Yii::$app->user->isGuest) {
            return $this->redirect('site/login');
        }else {
            if(Yii::$app->user->getIdentity()->tipoUtilizador=='Parque'){
                return $this->redirect('/parque/operacoes');
            }else {
                return $this->render('index');
            }
        }
    }


    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        $p = Yii::$app->request->post();
        if ($model->load($p)){
            if($model->login()) {
                return $this->redirect('/');
            }
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }



    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionMeuslocais()
    {
        return $this->render('meuslocais');
    }


    public function actionFaturas()
    {
        return $this->render('2faturas');
    }

}

basic/controllers/UtilizadorController.php
<?php

namespace app\controllers;

use app\models\LoginForm;
use app\models\Veiculo;
use Rhumsaa\Uuid\Uuid;
use Yii;
use app\models\Utilizador;
use app\models\UtilizadorSearch;
use yii\swiftmailer\Mailer;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UtilizadorController implements the CRUD actions for Utilizador model.
 */
class UtilizadorController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access1' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['create','sendmail','confirma'],
                'rules' => [
                    //'actions' => ['create', 'sendmail'],
                    [
                        'allow' => true,
                    ],
                ],
            ],
            'access2' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['index', 'delete'],
                'rules' => [
                    [
                        'actions' => ['index', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->getIdentity()->tipoUtilizador=='Admin';
                        }
                    ],
                    [
                        'actions' => ['index', 'delete'],
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'access3' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['view', 'update'],
                'rules' => [
                    [
                        'actions' => ['view', 'update'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            $request = Yii::$app->request;
                            $get = $request->get();
                            $id = $request->get('id');
                            return Yii::$app->user->getIdentity()->tipoUtilizador=='Admin'
                                    ||
                                   Yii::$app->user->id==$id;
                        }
                    ]
                ]
            ],

            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
              //      'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Utilizador models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UtilizadorSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Utilizador model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Utilizador model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Utilizador();
        $veiculo = new Veiculo();

        $model->authenticationKey = Uuid::uuid4().'';
        $loaded = $model->load(Yii::$app->request->post());

        if(yii::$app->user->isGuest) {
            $loaded = $loaded && $veiculo->load(Yii::$app->request->post());
            $model->estado = 'pendente';
        }
        $transaction = Yii::$app->db->beginTransaction();
        try {
            if ($loaded && $model->save()) {
                if (yii::$app->user->isGuest) {
                    $veiculo->id_utilizador = $model->id;
                    if ($veiculo->save()) {
                        $transaction->commit();
                        $this->sendmail($model);
                        return $this->redirect("/");
                    }
                }else{
                    $transaction->commit();
                }
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } catch (\Exception $e) {
            $transaction->rollBack();
            throw $e;
        }
        return $this->render('create', [
            'model' => $model,
            'veiculo'=>$veiculo,
        ]);

    }


    public function actionConfirma($auth){
        $model = Utilizador::find()->where(['authenticationKey'=>$auth])->one();

        if($model){
            if($model->estado!='pendente'){
                throw new NotFoundHttpException( yii::t('app','Email do utilizador {nome} já foi confirmado.',['nome'=>$model->getNomeCompleto()]));
                return;
            }
            $model->estado='activo';
            $model->save();

            {
                $l = new LoginForm();
                $l->username = $model->nome;
                $l->password = $model->senha;
                $l->rememberMe = true;
                $l->login();
                $this->redirect("/");
            }
        }else{
            throw new NotFoundHttpException(yii::t('app','Pagina pedida não existe.'));
        }

    }

    public function actionSendmail($id){
        $model = $this->findModel($id);
        $this->sendmail($model);
    }

    private function sendmail($model){
        $mail = new Mailer();
        \Yii::$app->mail->compose('utilizador/confirmation', ['nome' => $model->getNomeCompleto(), 'email'=>$model->email, 'auth'=>$model->authenticationKey])
            ->setFrom([\Yii::$app->params['adminEmail'] => 'ParkOnline'])
            ->setSubject('Register Confirmation' )
            ->setTo($model->email)
            ->send();
    }

    /**
     * Updates an existing Utilizador model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Utilizador model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Utilizador model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Utilizador the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Utilizador::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    const MIN_SEARCH_LEN=0;
    public function actionAutocomplete(){
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $value    =Yii::$app->getRequest()->getQueryParam('value');
        $offset   =Yii::$app->getRequest()->getQueryParam('offset');
        $minLength =self::MIN_SEARCH_LEN;
        if($minLength>0 && ($value=='' || strlen($value)<$minLength)) {
            return [__METHOD__.' precisa pelo menos '.$minLength.' caracteres, para proceder'];
            return;
        }

        $ret=array();

        if( !empty($id) || is_numeric($value)) {
            $val=!empty($id) ? $id : $value;
            $model = Utilizador::find()
                ->select("id,nome,apelido,email")
                ->where( ["id"=> intval($val)] )->all();
        }
        if (!isset($model) && empty($id)) {
            $offset= $offset==''
                ? strlen($value)
                : (intval($offset)<$minLength
                    ? $minLength
                    : intval($offset));
            $val=substr($value,0,$offset);

            $model = Utilizador::find()
                ->select("id,nome,apelido,email")
                ->where( $val==''?'':['like',"concat(nome,' ',apelido)" ,"$val"] )
                ->all();
        }
        if ($model !== null) {
            foreach($model as $k=>$rec) {
                $ret[] = array(
                    'label'=>$rec['id'].' - '.$rec['nome'].' '.$rec['apelido'].' - '.$rec['email'],
                    'value'=>$rec['id'],
                );
            }
        }
        return $ret;
    }
}

basic/views/site/2faturas.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Faturas';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="faturas">
    <h1><?= Html::encode($this->title) ?></h1>

    <h2>Lista de faturas por pagar</h2>
    <ul data-role="listview">
            	<li><a href="#">Praque + data</a></li>  
    </ul>

    <br><br>

    <!-- Faturas pagas -->
    <h2>Lista de faturas Págas</h2>
    <ul data-role="listview">
            <li><a href="#">Praque + data1</a></li>
            <li><a href="#">Praque + data2</a></li>
            <li><a href="#">Praque + data3</a></li>
            <li><a href="#">Praque + data4</a></li>
            <li><a href="#">Praque + data5</a></li>
    </ul>

</div>

basic/views/site/_ajax.php
<?=
\yii\helpers\Json::encode($data) ?>

basic/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = Yii::t('app','About');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        Trabalho de Grupo unidade curricular Integração de conhecimento<br>
        Turma SIWM 2016/2017
    </p>

</div>

basic/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

basic/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">
    <br>
    <br>

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        <?php echo Yii::t('app', 'The above error occurred while the Web server was processing your request.');?>
    </p>
    <p>
        <?php echo Yii::t('app', 'Please contact us if you think this is a server error. Thank you.');?>
    </p>

</div>

basic/views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use app\assets\MapAsset;

MapAsset::register($this);

$this->title = 'Localizar estacionamento';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="localiza-destino">
    <h1><?= Html::encode($this->title) ?></h1>

    <div id="box_input">
        <form id="obter-rota" class="ui-filterable">
            <label for="origem">Origem</label>
            <input id="origem" class="findplaces">
            <label for="destino">Destino</label>
            <input id="destino" class="findplaces">
            <button type="submit" class="btn btn-primary ui-btn ui-shadow ui-corner-all" name="rota">Obter rota</button>
        </form>
    </div>
    <div id="box_separator"></div>
    <div id="map"></div>
</div>

<script>
    $(document).ready(function() {
        // active resize of $map between $box_input and footer:first

        $('ul#list-local li').click(function () {
            var texto = $(this).find('a').text();
            $('#destino').val(texto);
            $("#list-local").listview("refresh");

            $("#list-local li").attr('class', '');
            $("#list-local li").addClass('ui-screen-hidden');
        });

        $('#destino').blur(function () {
            $("#list-local li").attr('class', '');
            $("#list-local li").addClass('ui-screen-hidden');
        });


        $('label[for=origem]').dblclick(function(){
            getMyGeoLocation(function(lat,lng,address){
                window.saveMode=true;
                $('#origem').val(address);
                setMarker("origem",lat,lng,address);
            })
        })

    });

</script>

basic/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('app','Entrar');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p><?= Yii::t('app','Please fill out the following fields to login:')?></p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton(Yii::t('app','Entrar'), ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                <?= Html::a(Yii::t('app','Create Utilizador'),['utilizador/create'], ['class' => '']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

</div>

basic/views/site/meuslocais.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Meus locais';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <div id="meus-locais">
        <img src="/img/emconstrucao.png" style="width: 98%" title="Em Construção" alt="Em Construção">
    </div>

</div>

basic/views/site/mostraparque.php
<?php

/* @var $this yii\web\View */
/* @var $get array */
/* @var $parque array */
/* @var $veiculos array */
/* @var $lugares array */
/* @var $reserva app\models\Reserva */


use yii\helpers\Html;

$this->title = $parque['nome'];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="mostraparque">

    <br>
    <image src= "https://cdn4.iconfinder.com/data/icons/banking-finance/32/walk-512.png" style= "width:50px; height:50px"><?= $get['distancia2'].', '.$get['tempo2'] ?>

    <image src= "https://d30y9cdsu7xlg0.cloudfront.net/png/72-200.png" style= "width:50px; height:50px"><?=$get['distancia1'].', '.$get['tempo1'] ?>
    <br>
    <br>
    <table align= "center" width= "400">


        <tr> <th colspan = "2"> Informações de ( <?=$parque['nome']?> )</th></tr>
        <tr>
            <th>Informação</th>
            <th>Resultado</th>
        </tr>

        <tr>
            <td>Data</td>
            <td><?=$reserva->data_reserva ?></td>
        </tr>
        <tr>
            <td>Preço por minuto</td>
            <td><?=$parque['preco_min'] ?>€</td>
        </tr>

        <tr>
            <td>Nº total de lugares</td>
            <td><?=$parque['total_lugares'] ?></td>
        </tr>


    </table>
    <br>
    <select id="tipo-lugar">
        <?php foreach($lugares as $lugar){?>
            <option value="<?=$lugar['id']?>"><?=$lugar['descricao']?></option>
        <?php } ?>
    </select>
    <br>
    <select id="veiculo">
        <?php foreach($veiculos as $veiculo){?>
            <option value="<?=$veiculo['id']?>"><?=$veiculo['marca'].' '.$veiculo['matricula']?></option>
        <?php } ?>
    </select>


    <!-- Reservar -->
    <button id="reservar" class="btn btn-primary ui-btn ui-shadow ui-corner-all" name="login-button">Reservar</button>


</div>

<script>
    $(document).ready(function(){
        $("button#reservar").click(function(e){
            var reserva_dat = {
                data_reserva:'<?=$reserva->data_reserva?>',
                id_veiculo:  $("select#veiculo").val(),
                id_parque:   <?=$reserva->id_parque?>,
                id_tipo_lugar:$("select#tipo-lugar").val(),
            };
            $.ajax({
                type: "GET",
                url: "/parque/reserva_pedido",
                data: reserva_dat ,
                dataType: "json",
                success:function(data,textStatus,jqXHR){
                    if(data['message']!='ok'){
                        if(typeof(data['message']) == 'string')
                            data['message']=[data['message']];
                        $.each(data['message'],function(i,mess){
                            window.alert( mess);
                        });
                    }else {
                        var url= '/parque/enviado_pedido/?id='+data.reserva.id;
                        //window.alert('redirect: '+url);
                        window.document.location.href=url;
                    }
                },
                error:function(jqXHR,textStatus,error){
                    window.alert(error);
                }

            });
        })
    })
</script>