basic/controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Reserva;
use app\models\Veiculo;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Parque;
use app\models\ParqueTipoLugar;
use yii\web\AssetManager;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'access2' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['mostraparque'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->getIdentity()->tipoUtilizador=='Condutor' ||
                            Yii::$app->user->getIdentity()->tipoUtilizador=='Admin' ;
                        }
                    ],
                    [
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['get'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionOnlineparks(){
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $model = Parque::find()->asArray()->all();
        return [
                'message'=>'ok',
                'parks'  =>$model
            ];
    }

    public function actionMostraparque(){
        $r = Yii::$app->request;
        /*
        $parqueId = $r->get('id');
        $origem   = $r->get('origem');
        $tempo1   = $r->get('tempo1');
        $distancia1= $r->get('distancia1');
        $destino   = $r->get('destino');
        $tempo2   = $r->get('tempo2');
        $distancia2= $r->get('distancia2');*/

        $parque = Parque::find()
                    ->innerJoin('parque_tipo_lugar','parque_tipo_lugar.id_parque=parque.id')
                    ->select('parque.*,sum(parque_tipo_lugar.total_lugares) as total_lugares')
                    ->where(['parque.id'=>$r->get('id'),
                    //         'parque_tipo_lugar.id_tipo_lugar'=>1
                    ])
                    ->asArray()->one();

        $lugares = ParqueTipoLugar::find()
                    ->innerJoin('tipo_lugar','tipo_lugar.id=parque_tipo_lugar.id_tipo_lugar')
                    ->select('parque_tipo_lugar.*,tipo_lugar.descricao')
                    ->where(['parque_tipo_lugar.id_parque'=>$r->get('id')])
                    ->asArray()->all();

        $veiculos = Veiculo::find()
                    ->where(['veiculo.id_utilizador'=>Yii::$app->user->id])
                    ->asArray()->all();


        $reserva = new Reserva();


        $reserva->data_reserva = date('Y-m-d H:i:s');;
        $reserva->id_parque= $r->get('id');

        return $this->render('mostraparque',[
            'get'=>$r->get(),
            'reserva'=>$reserva,
            'parque'=>$parque,
            'lugares'=>$lugares,
            'veiculos'=>$veiculos
        ]);
    }

    public function actionIndex()
    {
        if (\Yii::$app->user->isGuest) {
            return $this->redirect('site/login');
        }else {
            if(Yii::$app->user->getIdentity()->tipoUtilizador=='Parque'){
                return $this->redirect('/parque/operacoes');
            }else {
                return $this->render('index');
            }
        }
    }


    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        $p = Yii::$app->request->post();
        if ($model->load($p)){
            if($model->login()) {
                return $this->redirect('/');
            }
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }



    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionMeuslocais()
    {
        return $this->render('meuslocais');
    }


    public function actionFaturas()
    {
        return $this->render('2faturas');
    }

}

basic/controllers/VeiculoController.php
<?php

namespace app\controllers;

use app\models\Veiculo;
use Yii;
use app\models\Veiculo2;
use app\models\Veiculo2Search;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Connection;

/**
 * VeiculoController implements the CRUD actions for veiculo model.
 */
class VeiculoController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['admin'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->getIdentity()->tipoUtilizador=='Admin';
                        }
                    ],
                    [
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                ],
            ],

    
            'access2' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['index', 'view','create','update','delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->getIdentity()->tipoUtilizador=='Admin'
                                    ||
                                   Yii::$app->user->getIdentity()->tipoUtilizador=='Condutor';
                        }
                    ],
                    [
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                ],
            ],
            
        ];
    }

    /**
     * Lists all veiculo models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new Veiculo2Search();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,false);

        return $this->render('index', [
            'asAdmin'     =>false,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all veiculo models.
     * @return mixed
     */
    public function actionAdmin()
    {
        $searchModel = new Veiculo2Search();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,yii::$app->user->getIdentity()->tipoUtilizador=='Admin');

        return $this->render('index', [
            'asAdmin'     => yii::$app->user->getIdentity()->tipoUtilizador=='Admin',
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single veiculo model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        if(yii::$app->user->getIdentity()->tipoUtilizador!='Admin') {
            if (yii::$app->user->getIdentity()->tipoUtilizador == 'Condutor' && $model->id_utilizador != yii::$app->user->id)
                throw new ForbiddenHttpException(Yii::t('yii', 'Acesso negado.'));
        }
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new veiculo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new veiculo2();
        if(yii::$app->user->getIdentity()->tipoUtilizador=='Condutor' || yii::$app->request->get('admin') == false)
            $model->id_utilizador = yii::$app->user->id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'asAdmin'=> yii::$app->request->get('admin'),
            ]);
        }
    }

    /**
     * Updates an existing veiculo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if(yii::$app->user->getIdentity()->tipoUtilizador=='Condutor' && $model->id_utilizador!=yii::$app->user->id)
            throw new ForbiddenHttpException(Yii::t('yii', 'Acesso negado.'));


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'asAdmin'=> yii::$app->request->get('admin'),
            ]);
        }
    }

    /**
     * Deletes an existing veiculo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model=$this->findModel($id);
        if(yii::$app->user->getIdentity()->tipoUtilizador=='Condutor' && $model->id_utilizador!=yii::$app->user->id)
            throw new ForbiddenHttpException(Yii::t('yii', 'Acesso negado.'));

        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the veiculo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return veiculo2 the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        $model = veiculo2::find(true)->where(['veiculo.id'=>$id])->one();
        if ($model!== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    const MIN_SEARCH_LEN=0;
    public function actionAutocomplete(){
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $value    =Yii::$app->getRequest()->getQueryParam('value');
        $offset   =Yii::$app->getRequest()->getQueryParam('offset');
        $minLength =self::MIN_SEARCH_LEN;
        if($minLength>0 && ($value=='' || strlen($value)<$minLength)) {
            return [__METHOD__.' precisa pelo menos '.$minLength.' caracteres, para proceder'];
        }

        $ret=array();

        $model = Veiculo::find()
            ->select("id,matricula,marca,n_lugares");
        if( !empty($id) || is_numeric($value)) {
            $val=!empty($id) ? $id : $value;
            $model = $model->where( ["id"=> intval($val)] )->all();
        }else
        //if (!isset($model) && empty($id))
        {
            $offset= $offset==''
                ? strlen($value)
                : (intval($offset)<$minLength
                    ? $minLength
                    : intval($offset));
            $val=substr($value,0,$offset);

            $model = $model->where( $val==''?'':['like',"concat(matricula,' ',marca)" ,"$val"] )->all();
        }
        if ($model !== null) {
            foreach($model as $k=>$rec) {
                $ret[] = array(
                    'label'=>$rec['id'].' - '.$rec['marca'].' '.$rec['n_lugares'].' lugares / '.$rec['matricula'],
                    'value'=>$rec['id'],
                );
            }
        }
        return $ret;
    }
}

basic/views/layouts/main.old.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= "utf-8"//Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= \yii\helpers\Html::csrfMetaTags() ?>
    <title><?= \yii\helpers\Html::encode($this->title) ?></title>
    <?php $this->head() ?>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="//code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="/js/gmaps.js"></script>



    <link href='//fonts.googleapis.com/css?family=Convergence|Bitter|Droid+Sans|Ubuntu+Mono' rel='stylesheet' type='text/css' />

    <link rel="stylesheet" href="/css/jquery.mobile.icons.min.css" />
    <link rel="stylesheet" href="//code.jquery.com/mobile/1.4.5/jquery.mobile.structure-1.4.5.min.css" />
    <link rel="stylesheet" href="/css/parkonlinetest1.css" />
    <?php
    if(!empty(Yii::$app->controller->css)) :
        if(!is_array(Yii::$app->controller->css))
            Yii::$app->controller->css=[Yii::$app->controller->css];
            foreach(Yii::$app->controller->css as $cssFile) :
    ?>
                <link href='<?= $cssFile ?>' rel='stylesheet' type='text/css' />
    <?php
            endforeach;
        endif;
    ?>

    <?php
    if(!empty(Yii::$app->controller->javaScript)) :
        if(!is_array(Yii::$app->controller->javaScript))
            Yii::$app->controller->javaScript=[Yii::$app->controller->javaScript];
        foreach(Yii::$app->controller->javaScript as $javaScriptFile) :
            ?>
            <script type="text/javascript" src="<?= $javaScriptFile ?>"></script>
    <?php
        endforeach;
    endif;
    ?>

    <script>
        function initMap(){
            $(document).ready(function(){
                try{
                    initGMap()}
                catch(e){}
            })
        }
    </script>
    <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?v=3&language=pt&region=pt&callback=initMap&key=AIzaSyDUB6iRrkF2FGtTANln0okkSiNzA7jOFgg&libraries=places" async defer></script>

</head>
<body>
<?php $this->beginBody() ?>
<div class="wrap clearfix">
    <?php
    \yii\bootstrap\NavBar::begin([
        'brandLabel' => Yii::t('app','ParkOnline'),
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    if(! Yii::$app->user->isGuest){
        $nav=[
            [
                'label' =>  Yii::$app->user->getIdentity()->tipoUtilizador=='Admin'? 'Administrador':
                            Yii::$app->user->getIdentity()->tipoUtilizador,
                'url'   => '#',
                'items'=> array_merge(
                    (
                        Yii::$app->user->getIdentity()->tipoUtilizador!='Admin'?[]:
                        [
                                ['label' => 'Gestão Utilizadores', 'url' => '/utilizador'],
                                ['label' => 'Gestão Parques', 'url' => '/parque'],
                                '<li class="divider"></li>',
                        ]
                    ),
                    (
                       in_array(Yii::$app->user->getIdentity()->tipoUtilizador,['Admin','Condutor'])?
                        [
                                ['label' => 'Perfil', 'url' => '/utilizador/update?id='.Yii::$app->user->id],
                                ['label' => 'Dados do automovel', 'url' => '/veiculo'],
                                ['label' => 'Meus locais', 'url' => '/site/meuslocais'],
                                ['label' => 'Minhas reservas', 'url' => '/site/reservas'],
                                ['label' => 'Faturas', 'url' => '/site/faturas'],

                        ]:[]
                    ),
                    (
                        Yii::$app->user->getIdentity()->tipoUtilizador!='Parque'?[]:
                        [
                                ['label' => 'Operações', 'url' => '/parque/operacoes'],
                        ]
                    ),
                    (
                    [
                        '<li class="divider"></li>',
                        ['label' => 'Sair', 'url' => ['/site/logout']],
                    ]
                    )
                ),
            ],
            '<li class="divider"></li>',
            ['label' => Yii::t('app','Sobre'), 'url' => ['/site/about']],

        ];

        echo \yii\bootstrap\Nav::widget([
                            'options' => ['class' => 'navbar-nav navbar-left '],
                            'items' =>$nav
                        ]);
    }
    else
        \yii\bootstrap\Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-left'],
        'items' => [
            ['label' => 'Entrar', 'url' => ['/site/login']],
            ['label' => Yii::t('app','Sobre'), 'url' => ['/site/about']],
        ],
    ]);
    \yii\bootstrap\NavBar::end();
    ?>

    <div class="container">
        <?= \yii\widgets\Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>
<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; ParkOnline <?= date('Y') ?></p>

        <?php //include "share.php" ?>
    </div>
</footer>

<?php $this->endBody() ?>

<script type="text/javascript">
    $("h1").fitText(1.2, { maxFontSize: '36px' });
    $('.breadcrumb .active').fitText(1.2, {maxFontSize: '36px' });
    (function () {
        $.mobile.ajaxEnabled = false;
        $.mobile.loadingMessage = false;


        // handle bug on yii menu for small screens
        $('button[data-toggle=collapse]').click(function(e) {
            var target = $(this).data('target');
            if( $(target).hasClass('in') ) {
                //$(target).removeClass('in',{duration:500});
                $(target).removeClass('in');
                return false;
            }else{
                $(target).addClass('in');
                $(target).find('li.dropdown').addClass('open');
                return false
            }
        });

        $('ul.navbar-nav li.dropdown').click(function(e){
            var o=$(this);
            o.toggleClass('open');
        })

    }());

</script>

</body>
</html>
<?php $this->endPage() ?>

basic/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= "utf-8"//Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= \yii\helpers\Html::csrfMetaTags() ?>
    <title><?= \yii\helpers\Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <link rel="stylesheet" href="/css/parkonlinetest1.css" />
    <?php
    if(!empty(Yii::$app->controller->css)) :
        if(!is_array(Yii::$app->controller->css))
            Yii::$app->controller->css=[Yii::$app->controller->css];
            foreach(Yii::$app->controller->css as $cssFile) :
    ?>
                <link href='<?= $cssFile ?>' rel='stylesheet' type='text/css' />
    <?php
            endforeach;
        endif;
    ?>

    <?php
    if(!empty(Yii::$app->controller->javaScript)) :
        if(!is_array(Yii::$app->controller->javaScript))
            Yii::$app->controller->javaScript=[Yii::$app->controller->javaScript];
        foreach(Yii::$app->controller->javaScript as $javaScriptFile) :
            ?>
            <script type="text/javascript" src="<?= $javaScriptFile ?>"></script>
    <?php
        endforeach;
    endif;
    ?>

    <script>
        function initMap(){
            $(document).ready(function(){
                try{
                    initGMap()}
                catch(e){}
            })
        }
    </script>
    <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?v=3&language=pt&region=pt&callback=initMap&key=AIzaSyDUB6iRrkF2FGtTANln0okkSiNzA7jOFgg&libraries=places" async defer></script>

</head>
<body>
<?php $this->beginBody() ?>
<div class="wrap clearfix">
    <?php
    \yii\bootstrap\NavBar::begin([
        'brandLabel' => Yii::t('app','ParkOnline'),
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    if(! Yii::$app->user->isGuest){
        $esdadosItems=[];
        if( in_array(Yii::$app->user->getIdentity()->tipoUtilizador,['Admin','Condutor']) ){
            $estadosCount = \app\models\ReservaEstado::getCountReservas()->all();
            foreach($estadosCount as $idx=>$esdadoItem) {
                $esdadosItems[] = [
                    'label' =>  '<span class="submenu-estados">'     .$esdadoItem->descricao  . '</span>'.
                                '<span class="submenu-estados-ct"> ('.$esdadoItem->ct_reservas.')</span>',
                    'encode' => false,
                    'url' => '/reserva/estado/' . strtolower($esdadoItem->descricao)
                ];
            }
        }else if( in_array(Yii::$app->user->getIdentity()->tipoUtilizador,['Parque']) ){
            $estadosCount = \app\models\ReservaEstado::getCountReservasParque()->all();
            foreach($estadosCount as $idx=>$esdadoItem) {
                $esdadosItems[] = [
                    'label' =>  '<span class="submenu-estados">'     .$esdadoItem->descricao  . '</span>'.
                                '<span class="submenu-estados-ct"> ('.$esdadoItem->ct_reservas.')</span>',
                    'encode' => false,
                    'url' => '/reserva/estado/' . strtolower($esdadoItem->descricao)
                ];
            }
        }
        $nav=[
            [
                'label' =>  '<div class="menu-left-l1">'.(Yii::$app->user->getIdentity()->tipoUtilizador=='Admin'? 'Administrador':
                                                        Yii::$app->user->getIdentity()->tipoUtilizador) .'</div>'.
                            '<div class="menu-left-l2">'.yii::$app->user->getIdentity()->getNomeCompleto().'</div>',
                'url'   => '#',
                'encode'=> false,
                'items'=> array_merge(
                    (
                        Yii::$app->user->getIdentity()->tipoUtilizador!='Admin'?[]:
                        [
                                ['label' => 'Gestão Utilizadores', 'url' => '/utilizador'],
                                ['label' => 'Gestão Veiculos', 'url' => '/veiculo/admin'],
                                ['label' => 'Gestão Parques', 'url' => '/parque'],
                                ['label' => 'Gestão Reservas', 'url' => '/reserva'],
                                '<li class="divider"></li>',
                        ]
                    ),
                    (
                       in_array(Yii::$app->user->getIdentity()->tipoUtilizador,['Admin','Condutor'])?
                        [
                                ['label' => 'Perfil', 'url' => '/utilizador/update?id='.Yii::$app->user->id],
                                ['label' => 'Dados do automovel', 'url' => '/veiculo'],
                                ['label' => 'Meus locais', 'url' => '/site/meuslocais'],
                                ['label' => 'Minhas reservas', 'url' => '/reserva/estado/aprovado',
                                        'items'=> $esdadosItems
                                ],
                                  /*
                                            [
                                                ['label' => 'Pendente', 'url' => '/reserva/estado/pendente'],
                                                ['label' => 'Aprovado', 'url' => '/reserva/estado/aprovado'],
                                                ['label' => 'Rejeitado', 'url' => '/reserva/estado/rejeitado'],
                                                ['label' => 'Dentro', 'url' => '/reserva/estado/dentro'],
                                                ['label' => 'Fora', 'url' => '/reserva/estado/fora'],
                                                ['label' => 'Expirado', 'url' => '/reserva/estado/expirado']
                                            ]
                                  */

                                ['label' => 'Faturas', 'url' => '/site/faturas'],

                        ]:[]
                    ),
                    (
                        Yii::$app->user->getIdentity()->tipoUtilizador!='Parque'?[]:
                        [
                                ['label' => 'Operações', 'url' => '/parque/operacoes'],
                                ['label' => 'Reservas',
                                    'items'=> $esdadosItems
                                ],
                        ]
                    ),
                    (
                    [
                        '<li class="divider"></li>',
                        ['label' => 'Sair', 'url' => ['/site/logout']],
                    ]
                    )
                ),
            ],
            '<li class="divider"></li>',
            ['label' => Yii::t('app','Sobre'), 'url' => ['/site/about']],

        ];

        echo \yii\bootstrap\Nav::widget([
                            'options' => ['class' => 'navbar-nav navbar-left '],
                            'items' =>$nav
                        ]);
    }
    else
        \yii\bootstrap\Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-left'],
        'items' => [
            ['label' => 'Entrar', 'url' => ['/site/login']],
            ['label' => Yii::t('app','Sobre'), 'url' => ['/site/about']],
        ],
    ]);
    \yii\bootstrap\NavBar::end();
    ?>

    <div class="container">
        <?= \yii\widgets\Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>
<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; ParkOnline <?= date('Y') ?></p>

        <?php //include "share.php" ?>
    </div>
</footer>

<?php $this->endBody() ?>

<script type="text/javascript">
    $("h1").fitText(1.2, { maxFontSize: '36px' });
    $('.breadcrumb .active').fitText(1.2, {maxFontSize: '36px' });
    (function () {
        $.mobile.ajaxEnabled = false;
        $.mobile.loadingMessage = false;


        // handle bug on yii menu for small screens
        $('button[data-toggle=collapse]').click(function(e) {
            var target = $(this).data('target');
            if( $(target).hasClass('in') ) {
                //$(target).removeClass('in',{duration:500});
                $(target).removeClass('in');
                return false;
            }else{
                $(target).addClass('in');
                $(target).find('li.dropdown').addClass('open');
                return false
            }
        });

/*        $('ul.navbar-nav li.dropdown').click(function(e){
            var o=$(this);
            o.toggleClass('open');
            e.preventDefault();
            return false;
        })*/

    }());

</script>

</body>
</html>
<?php $this->endPage() ?>